export const arTranslations = {
  login: "تسجيل الدخول",
  identityNumber: "رقم الهوية",
  password: "كلمة المرور",
  loginButton: "تسجيل الدخول",
  invalidCredentialsTitle: "تسجيل الدخول غير ناجح.",
  invalidCredentialsMessage: "اسم مستخدم أو كلمة مرور غير صالحة",
  confirmPhotos: "تأكيد الصورة",
  takePicture: "التقاط صورة",
  loginSuccesfulTitle: "تم الدخول بنجاح",
  loginSuccesfulMessage:
    "سيتم توجيهك إلى شاشة التحقق من الوجه، يرجى التأكد من وجود كافٍ من الضوء في بيئتك.",
  alertOK: "حسنًا",
  faceAuthenticationSuccessfulTitle: "المصادقة عن طريق الوجه ناجحة",
  faceAuthenticationSuccessfulMessage:
    "سيتم توجيهك إلى شاشة تأكيد الرسائل القصيرة",
  backButton: "عودة",
  GSMAuthenticationSuccessfulTitle: "تم التحقق من الرسائل القصيرة بنجاح",
  GSMAuthenticationMessage:
    "سيتم توجيهك إلى شاشة التحقق من الموقع، يرجى التأكد من تفعيل خدمات الموقع.",
  SMSNotConfirmedTitle: "فشل التحقق من الرسائل القصيرة",
  SMSNotConfirmedMessage: "الرمز الذي قمت بإدخاله غير صحيح",
  GSMSendCodeButtonText: "إرسال رمز التحقق",
  GSMCodeSentMessage: "تم إرسال رمز التحقق إلى هاتفك.",
  enterCodePlaceholder:
    "الرجاء إدخال الرمز المكون من 6 أرقام الذي تم استلامه عبر الرسالة القصيرة",
  confirmGSMCodeButtonText: "تأكيد",
  locationPermissionDenined: "خدمة الموقع مغلقة",
  languagePickerLabel: "اللغة الرجاء اختيار",
  faceAuthenticationFailedTitle: "فشل التحقق من الوجه",
  faceAuthenticationFailedMessage: "يرجى إعادة التقاط الصور وفقًا للتوجيهات",
  confirmLocationButtonText: "تأكيد الموقع",
  logout: "تسجيل الخروج",
  locationAuthenticationTitle: "موقعك",
  startConfirmationButtonText: "بدء التأكيد",
  lookFront:
    "يرجى النقر على زر بدء التأكيد والنظر إلى الكاميرا حتى يهتز هاتفك.",
  lookLeft: "يرجى النظر لليسار حتى يهتز هاتفك.",
  lookRight: "يرجى النظر لليمين حتى يهتز هاتفك.",
  waitForFaceConfirmation: "يرجى الانتظار لعملية تأكيد الوجه...",
  yourConfirmationCode: "رمز التأكيد الخاص بك:",
  enterConfirmationCode: "الرجاء إدخال هذا الرمز والضغط على زر تأكيد.",
  alertCopy: "نسخ الرمز",
  country: "الدولة",
  region: "المنطقة",
  subregion: "المنطقة الفرعية",
  district: "الحي",
  postalCode: "الرمز البريدي",
  locationConfirmationUnsuccessfulTitle: "تأكيد الموقع غير ناجح",
  locationConfirmationUnsuccessfulMessage:
    "لا يمكن تأكيد موقعك، يرجى المحاولة مرة أخرى.",
  allConfirmationsSuccessfulMessage: "اكتملت عملية التأكيد بنجاح.",
  startConfirmation: "بدء التأكيد",
  profileInformations: "معلومات الملف الشخصي",
  errorIdentityNumberRequired: "رقم الهوية مطلوب.",
  errorPasswordRequired: "كلمة المرور مطلوبة.",
  errorPasswordLength: "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.",
  mainPage: "الصفحة الرئيسية",
  profileInformation: "معلومات الملف الشخصي",
  firstName: "الاسم الأول",
  lastName: "اسم العائلة",
  phoneNumber: "رقم الهاتف",
  email: "البريد الإلكتروني",
  mockLocationTitle: "تم اكتشاف تطبيق الموقع الوهمي!",
  mockLocationMessage:
    "أنت تحاول تأكيد موقعك عبر تطبيق الموقع الوهمي. يرجى إيقاف تشغيل تطبيق الموقع الوهمي!",
  Turkish: "تركيا",
  English: "الإنجليزية",
  Arabic: "العربية",
  errorIdentityNumberInvalid: "A Identity Number Invalid",
  cellTowerLocation: "Arapça Baz İstasyonu Konumu",
  locationAuthFailedTitle: "فشل التحقق من الموقع",
  locationAuthFailedMessage:
    "تعذر التحقق من موقعك، يرجى التأكد من أنك في الموقع المحدد في صفحة الملف الشخصي وأعد بدء عملية التحقق مرة أخرى.",
  noAccessToCamera: "arapça kameraya erişim yok",
};
