export const enTranslations = {
  login: "Login",
  identityNumber: "Identity Number",
  password: "Password",
  loginButton: "Login",
  invalidCredentialsTitle: "Login Unsuccessful ",
  invalidCredentialsMessage: "Invalid username or password",
  confirmPhotos: "Confirm Photo",
  takePicture: "Take Picture",
  loginSuccesfulTitle: "Login Succesful",
  loginSuccesfulMessage:
    "You will be directed to the face verification screen, please make sure there is sufficient light in your environment.",
  alertOK: "OK",
  faceAuthenticationSuccessfulTitle: "Face Authentication Successful",
  faceAuthenticationSuccessfulMessage:
    "You will be directed to the SMS confirmation screen",
  backButton: "Back",
  GSMAuthenticationSuccessfulTitle: "SMS Verification Successful",
  GSMAuthenticationMessage:
    "You will be redirected to the location verification screen, please make sure that location services are enabled.",
  SMSNotConfirmedTitle: "SMS Verification Unsuccessful",
  SMSNotConfirmedMessage: "The verification code you entered is incorrect",
  GSMSendCodeButtonText: "Send Verification Code",
  GSMCodeSentMessage: "Verification code sent to your phone.",
  enterCodePlaceholder: "Enter the 6-digit code from the SMS",
  confirmGSMCodeButtonText: "Confirm",

  locationPermissionDenined: "Location Permission Denied",

  languagePickerLabel: "Choose Language",
  faceAuthenticationFailedTitle: "Face Authentication Failed",
  faceAuthenticationFailedMessage:
    "Please retake the photos following the instructions correctly",
  confirmLocationButtonText: "Confirm Location",
  logout: "Logout",
  locationAuthenticationTitle: "Your Location",
  startConfirmationButtonText: "Start Confirmation",
  lookFront:
    "Please press Start Confirmation button and look at the camera until your phone vibrates.",
  lookLeft: "Please look to the left until your phone vibrates.",
  lookRight: "Please look to the right until your phone vibrates.",
  waitForFaceConfirmation: "Please wait for face confirmation process...",
  yourConfirmationCode: "Your Confirmation Code:",
  enterConfirmationCode: "Plase enter this code and press Confirm button. ",
  alertCopy: "Copy Code",
  country: "Country",
  region: "Region",
  subregion: "Subregion",
  district: "District",
  postalCode: "Postal Code",
  locationConfirmationUnsuccessfulTitle: "Location Cannot Confirmed",
  locationConfirmationUnsuccessfulMessage:
    "Your location cannot confirmed plesa try again.",
  allConfirmationsSuccessfulMessage:
    "Your confirmation process finished successfully.",
  startConfirmation: "Start Confirmation",
  profileInformations: "Profile Informations",
  errorIdentityNumberRequired: "Identity Number is required.",
  errorPasswordRequired: "Password is required.",
  errorPasswordLength: "Password must be at least 6 characters.",
  mainPage: "Main Page",
  profileInformation: "Profile Information",
  firstName: "First Name",
  lastName: "Last Name",
  phoneNumber: "Phone Number",
  email: "E-Mail",
  mockLocationTitle: "Mock Location App Detected!",
  mockLocationMessage:
    "You are trying to confirm your location via Mock Location App. Please turn off Mock Location App!",
  Turkish: "Turkish",
  English: "English",
  Arabic: "Arabic",
  errorIdentityNumberInvalid: "Identity Number Invalid",
  unreadNotifications: "Unread Notifications",
  readNotifications: "Read Notifications",
  cellTowerLocation: " Cell Tower Location",
};
