export const trTranslations = {
  login: "Giriş",
  identityNumber: "Kimlik Numarası",
  password: "Parola",
  loginButton: "Giriş",
  invalidCredentialsTitle: "Giriş Başarısız",
  invalidCredentialsMessage: "Geçersiz Kullanıcı Adı veya Parola",
  confirmPhotos: "Fotoğrafı Doğrula",
  takePicture: "Fotoğraf Çek",
  loginSuccesfulTitle: "Giriş Başarılı",
  loginSuccesfulMessage:
    "Yüz doğrulama ekranına yönlendirileceksiniz, lütfen bulunduğunuz ortamda yeterli ışık olduğundan emin olun.",
  alertOK: "Tamam",
  faceAuthenticationSuccessfulTitle: "Yüz Doğrulama Başarılı",
  faceAuthenticationSuccessfulMessage:
    "SMS doğrulama ekranına yönlendirileceksiniz...",
  backButton: "Geri",
  GSMAuthenticationSuccessfulTitle: "SMS Doğrulama Başarılı",
  GSMAuthenticationMessage:
    "Konum doğrulama ekranına yönlendirileceksiniz, lütfen konum servislerinin açık olduğundan emin olun.",
  SMSNotConfirmedTitle: "SMS Doğrulama Başarısız",
  SMSNotConfirmedMessage: "Girdiğiniz doğrulama kodu yanlış",
  GSMSendCodeButtonText: "Doğrulama Kodu Gönder",
  GSMCodeSentMessage: "Doğrulama kodu telefonunuza gönderildi.",
  enterCodePlaceholder: "Gelen SMS teki 6 haneli kodu giriniz",
  confirmGSMCodeButtonText: "Doğrula",

  locationPermissionDenined: "Konum Servisi Kapalı",
  languagePickerLabel: "Dil Seçiniz",
  faceAuthenticationFailedTitle: "Yüz Doğrulama Başarısız",
  faceAuthenticationFailedMessage:
    "Lütfen direktiflere uygun biçimde fotoğrafları tekrar çekiniz",

  confirmLocationButtonText: "Konum Doğrula",
  logout: "Çıkış",
  locationAuthenticationTitle: "Konumunuz",
  startConfirmationButtonText: "Yüz Doğrulamayı Başlat",
  lookFront:
    "Lütfen Yüz Doğrulamayı Başlat butonuna basın ve telefonunuz titreşene kadar kameraya bakınız.",
  lookLeft: "Lütfen telefonunuz titreşene kadar sola bakınız.",
  lookRight: "Lütfen telefonunuz titreşene kadar sağa bakınız.",
  waitForFaceConfirmation:
    "Lütfen yüz tanıma işlemi sonuçlanana kadar bekleyiniz...",
  yourConfirmationCode: "Doğrulama Kodunuz:",
  enterConfirmationCode: "Lütfen kodunuzu girip Doğrula butonuna basınız. ",
  alertCopy: "Kodu Kopyala",
  country: "Ülke",
  region: "Şehir",
  subregion: "İlçe",
  district: "Semt",
  postalCode: "Posta Kodu",
  locationConfirmationUnsuccessfulTitle: "Konum Doğrulanamadı",
  locationConfirmationUnsuccessfulMessage:
    "Konumunuz doğrulanamadı lütfen tekrar deneyiniz.",
  allConfirmationsSuccessfulMessage:
    "Doğrulama işleminiz başarıyla sonuçlanmıştır.",
  startConfirmation: "Doğrulamaya Başla",
  profileInformations: "Profil Bilgileri",
  errorIdentityNumberRequired: "Kimlik numarası boş olamaz",
  errorPasswordRequired: "Parola boş olamaz",
  errorPasswordLength: "Parola en az 6 karakter olmalı.",
  mainPage: "Anasayfa",
  profileInformation: "Profil Bilgileri",
  firstName: "İsim",
  lastName: "Soyisim",
  phoneNumber: "Telefon",
  email: "E-Mail",
  mockLocationTitle: "Sahte Konum Uygulaması Tespit Edildi!",
  mockLocationMessage:
    "You are trying to confirm your location via Mock Location App. Please turnf off Mock Location APP! ",
  Turkish: "Türkçe",
  English: "İngilizce",
  Arabic: "Arapça",
  errorIdentityNumberInvalid: "Kimlik Numarası Geçersiz",
  unreadNotifications: "Okunmamış Bildirimler",
  readNotifications: "Okunmuş Bildirimler",
  cellTowerLocation: "Cihaz IP Bazlı Konum",
  locationAuthFailedTitle: "Konum Doğrulama Başarısız",
  locationAuthFailedMessage:
    "Konumunuz doğrulanamadı lütfen Profil Bilgileri sayfasında tanımlanmış olan konumda bulunduğunuzdan emin olun ve doğrulama işlemine baştan başlayın.",
  noAccessToCamera: "Kamera erişimi yok",
  AppName: "Adli Kontrol Sistemi",
  notifications: "Bildirimler",
  GSMAuthenticationInfo:
    "Doğrulama Kodu Gönder butonuna bastığınızda kayıtlı telefon numaranıza doğrulama kodu gelecektir.",
  faceAuthenticationHeader: "Yüz Doğrulama",
  GSMConfirmationHeader: "SMS Doğrulama",
  LocationConfirmationHeader: "Konum Doğrulama",
  helpHeader: "Yardım",
  settingsHeader: "Ayarlar",
};
